### ISSUE TITLE
Question: Possibility to process multiple files at once?

### ISSUE THREAD

**Issue by triagony** [baltpeter/scanprep#1]
Hi! 

Is it somehow possible to process multiple pdf files at once, e.g. with `scanprep *.pdf [output_dir]`?

Kind regards

**Comment by baltpeter** [comment]
Hi!

That is not currently implemented, no. I also don't see a way of implementing that without breaking backwards compatibility as there would then be no way to distinguish between the (optional) output directory and the last file (unless we passed the glob as a string and then parsed that in scanprep of course, but I would prefer to avoid that).

However, you can simply do a shell loop like this:

```sh
for f in *.pdf; do scanprep "$f" output_dir; done
```

**Comment by triagony** [comment]
Thank you! That's good enough for me - at the end of the day, it's the result that counts :)
